In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = [{'Stuart': 10, 'Lucy': 8, 'David': 13, 'Alexa': 11,},
        {'Stuart': 12, 'Lucy': 11, 'David': 18, 'Alexa': 12, 'Ben': 22,},
        {'Stuart': 14, 'Lucy': 15, 'David': 20, 'Alexa': 13,},
        {'Stuart': 17, 'Lucy': 19, 'David': 22, 'Alexa': 14, 'Ben': 24},]

results = pd.DataFrame(data, index=['first', 'second', 'third', 'fourth'])

In [ ]:
results

In [ ]:
results['parents'] = results['David'] + results['Lucy']
results

In [ ]:
import pandas as pd
import numpy as np

#Create a Dictionary of series
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

#Create a DataFrame
df = pd.DataFrame(d)
print ("Our data series is:")
print(df)

In [ ]:
df.T

In [ ]:
df.T.values

In [ ]:
df.values

In [ ]:
df.keys

In [ ]:
df.items

In [ ]:
        import copy

        def replacing_list(lst, to_replace, rep, in_place=True):
            if not in_place:
                lst = copy.deepcopy(lst)
            for idx, entry in enumerate(lst):
                if entry == to_replace:
                    lst[idx] = rep
                elif isinstance(entry, list):
                    replacing_list(entry, to_replace, rep)
            if not in_place:
                return lst


        tests = [([10, 20, 30], 20, 55),
                 (['Mary', 'had', 'a', 'little', 'lamb'], 'lamb', 'dog'),
                 ([['Mary', 'Wendy', 'Mary'], 67, 'Mary', 49, 'Mary', 'Helen', 21], 'Mary', 'Mike'),
                 ([1, 2, 3, [10, 20, 40], 4, 5], [10, 20, 40], {'name': 'me', 'age': 10})]

        for list_, target, replacement in tests:
            print('Returned:', replacing_list(list_, target, replacement, in_place=False))
            print('Original:', list_)
            replacing_list(list_, target, replacement)
            print('Replaced:', list_)
            print()

In [ ]:
    import pyodbc
    import pandas as pd

    cnxn = pyodbc.connect('DRIVER={{Microsoft Access Driver (*.mdb, *.accdb)}};DBQ=' + \
                          '{};Uid={};Pwd={};'.format(db_file, user, password)

    query = "SELECT * FROM mytable WHERE INST = '796116'"
    dataf = pd.read_sql(query, cnxn)
    cnxn.close()

In [ ]:
import ast

test = "((23,45,45),(23,45,45))"

result = T('((1, 2, 3),(4, 5, 6))')

print(result, type(result))
print(len(result) == 2)
print(all(len(t) == 3 for t in result))

In [36]:
#!/usr/bin/python3.6

def M_1():
    print('\n\nYou chose option 1.\nThat gives you another menu:')
    return 'M_1'

def M_2():
    print('\n\nYou chose option 2.\nDoes some stuff and returns you to same menu.')
    
def M_3():
    print('\n\nYou chose option 3.\nDoes some other stuff and returns you to same menu.')
    
def M1_a():
    print('\n\nNow you get a sub-menu full of more exciting options:')
    return 'M1'

def M1_b():
    print('\n\nYou chose option B of sub-menu.\nDoes some stuff and returns you to same menu.')

def M1_print():
    print('\n\nYour choice would do something exciting like print a report.')
    print('Then take you back to the same menu. Bye.')
    
def menu_choice(prompt, choices, case_sensitive):
    while True:
        print(prompt, end='')
        response = input() if case_sensitive else input().lower()
        if response and response in choices.keys():
            return response
        print('Not a valid choice. Please try again.')
    
def menu_present(menu_level):
    menu = menus.get(menu_level)
    option = menu_choice(menu['prompt'], menu['choices'], menu['case_sensitive'])
    action = menu['choices'].get(option)
    return option, action
    
menus = {'Master': {
            'choices': {'1': M_1, '2': M_2, '3': M_3, 'q': None},
            'prompt': "\n\nMENU\n1. One\n2. Two\n3. Three\nq. Quit\nChoice? ",
            'case_sensitive': False,
            'parent': 'Master'
            },
        'M_1': {
            'choices': {'a': M1_a, 'b': M1_b, 'u': None, 'q': None},
            'prompt': "\n\nSub-Menu 1\nA. Alpha\nB. Beta\nu. Up\nq. Quit\nChoice? ",
            'case_sensitive': False,
            'parent': 'Master'
            },
        'M1': {
            'choices': {'p': M1_print, 'u': None},
            'prompt': "\n\nSub-sub-menu XXX\nP. Print\nu. Up\nChoice? ",
            'case_sensitive': False,
            'parent': 'M_1'
            }
        }

menu_level = "Master"

while True:
    option, action = menu_present(menu_level)
    if not action:
         if option.lower() == 'q':
             break
         if option.lower() == 'u':
             menu_level = menus[menu_level]['parent']
    else:
        outcome = action()
        if outcome:
            menu_level = outcome

MENU
1. One
2. Two
3. Three
q. Quit
Choice? 3


You chose option 3.
Does some other stuff and returns you to same menu.


MENU
1. One
2. Two
3. Three
q. Quit
Choice? 2


You chose option 2.
Does some stuff and returns you to same menu.


MENU
1. One
2. Two
3. Three
q. Quit
Choice? 1


You chose option 1.
That gives you another menu:


Sub-Menu 1
A. Alpha
B. Beta
u. Up
q. Quit
Choice? B


You chose option B of sub-menu.
Does some stuff and returns you to same menu.


Sub-Menu 1
A. Alpha
B. Beta
u. Up
q. Quit
Choice? A


Now you get a sub-menu full of more exciting options:


Sub-sub-menu XXX
P. Print
u. Up
Choice? p


Your choice would do something exciting like print a report.
Then take you back to the same menu. Bye.


Sub-sub-menu XXX
P. Print
u. Up
Choice? p


Your choice would do something exciting like print a report.
Then take you back to the same menu. Bye.


Sub-sub-menu XXX
P. Print
u. Up
Choice? u


Sub-Menu 1
A. Alpha
B. Beta
u. Up
q. Quit
Choice? b


You chose option B of sub-menu.
Does some stuff and returns you to same menu.


Sub-Menu 1
A. Alpha
B. Beta
u. Up
q. Quit
Choice? u


MENU
1. One
2. Two
3. Three
q. Quit
Choice? 1


You chose option 1.
That gives you another menu:


Sub-Menu 1
A. Alpha
B. Beta
u. Up
q. Quit
Choice? q

In [60]:
fruit_ = ['Banana 5', 'Apple 6', 'Pears 4', 'Melon 6', 'Lemon 4']
fruits = {fruit: int(qty_str) 
          for fruit, qty_str in [fruity.split()
          for fruity in fruit_]}
largest = max(fruits.values())
print(f'The following fruits are the most common, appearing {largest} times: ')
print(*(fruit for fruit, qty in fruits.items() if qty == largest), sep=', ')

The following fruits are the most common, appearing 6 times:
Apple, Melon

In [55]:
fruited

{'Banana': 5, 'Apple': 6, 'Pears': 4, 'Melon': 8, 'Lemon': 4}

In [13]:
    import periodictable as pt

    d = {el.symbol: el._mass for el in pt.elements}

    def molecular_mass(chemical_formula):
        mass = 0
        name = ''
        num = 0
        i = 0
        for next_char in chemical_formula:
            print(f'next_char: {next_char}') 
            name += next_char
            print(f'name: {name}') 
            i += 1
            print(f'i: {i}')
            if i > 2:
                if name[-1].isupper():
                    name = name[0:-1]
                    if name[1].islower():
                        mass += d[name[:2]] * int(name[2:])
                    else:
                        mass +=  d[name[0]] * int(name[1:])
                    name = next_char
                    i = 0

        return mass

    print(molecular_mass('K2Cr2O7'))

next_char: K
name: K
i: 1
next_char: 2
name: K2
i: 2
next_char: C
name: K2C
i: 3
next_char: r
name: Cr
i: 1
next_char: 2
name: Cr2
i: 2
next_char: O
name: Cr2O
i: 3
next_char: 7
name: O7
i: 1
182.18880000000001

In [11]:
d

{'n': 1.00866491597,
 'H': 1.00794,
 'He': 4.002602,
 'Li': 6.941,
 'Be': 9.012182,
 'B': 10.811,
 'C': 12.0107,
 'N': 14.0067,
 'O': 15.9994,
 'F': 18.9984032,
 'Ne': 20.1797,
 'Na': 22.98977,
 'Mg': 24.305,
 'Al': 26.981538,
 'Si': 28.0855,
 'P': 30.973761,
 'S': 32.065,
 'Cl': 35.453,
 'Ar': 39.948,
 'K': 39.0983,
 'Ca': 40.078,
 'Sc': 44.95591,
 'Ti': 47.867,
 'V': 50.9415,
 'Cr': 51.9961,
 'Mn': 54.938049,
 'Fe': 55.845,
 'Co': 58.9332,
 'Ni': 58.6934,
 'Cu': 63.546,
 'Zn': 65.409,
 'Ga': 69.723,
 'Ge': 72.64,
 'As': 74.9216,
 'Se': 78.96,
 'Br': 79.904,
 'Kr': 83.798,
 'Rb': 85.4678,
 'Sr': 87.62,
 'Y': 88.90585,
 'Zr': 91.224,
 'Nb': 92.90638,
 'Mo': 95.94,
 'Tc': 98,
 'Ru': 101.07,
 'Rh': 102.9055,
 'Pd': 106.42,
 'Ag': 107.8682,
 'Cd': 112.411,
 'In': 114.818,
 'Sn': 118.71,
 'Sb': 121.76,
 'Te': 127.6,
 'I': 126.90447,
 'Xe': 131.293,
 'Cs': 132.90545,
 'Ba': 137.327,
 'La': 138.9055,
 'Ce': 140.116,
 'Pr': 140.90765,
 'Nd': 144.24,
 'Pm': 145,
 'Sm': 150.36,
 'Eu': 151.964,
 'Gd': 157.25,
 'Tb': 158.92534,
 'Dy': 162.5,
 'Ho': 164.93032,
 'Er': 167.259,
 'Tm': 168.93421,
 'Yb': 173.04,
 'Lu': 174.967,
 'Hf': 178.49,
 'Ta': 180.9479,
 'W': 183.84,
 'Re': 186.207,
 'Os': 190.23,
 'Ir': 192.217,
 'Pt': 195.078,
 'Au': 196.96655,
 'Hg': 200.59,
 'Tl': 204.3833,
 'Pb': 207.2,
 'Bi': 208.98038,
 'Po': 209,
 'At': 210,
 'Rn': 222,
 'Fr': 223,
 'Ra': 226,
 'Ac': 227,
 'Th': 232.0381,
 'Pa': 231.03588,
 'U': 238.02891,
 'Np': 237,
 'Pu': 244,
 'Am': 243,
 'Cm': 247,
 'Bk': 247,
 'Cf': 251,
 'Es': 252,
 'Fm': 257,
 'Md': 258,
 'No': 259,
 'Lr': 262,
 'Rf': 261,
 'Db': 262,
 'Sg': 266,
 'Bh': 264,
 'Hs': 277,
 'Mt': 268,
 'Ds': 281,
 'Rg': 272,
 'Cn': 285,
 'Nh': 286,
 'Fl': 289,
 'Mc': 289,
 'Lv': 293,
 'Ts': 294,
 'Og': 294}

In [15]:
num1 = float(input("Enter first number: "))
op = input("Enter  operator: ")
num2 = float(input("Enter second number: "))
 
if op == "+":
    print(num1 + num2)
elif op == "-":
    print(num1 - num2)
elif op == "/":
    print(num1 / num2)
elif op == "*":
    print(num1 * num2)
else:
    print("Invalid operator")

Enter first number: 2
Enter  operator: +
Enter second number: 3
5.0

In [19]:
'adds some text to the beginning of a file, and moves the'
'rest of the content down the file'

new_text = 'This is new text with a 😮 to make you laugh'
buffer = new_text.encode('utf-8')
size = len(buffer)

with open('buffer.txt', 'r+b') as f:
    while buffer:
        next_buffer = f.read(size)
        f.seek(-len(next_buffer), 1)
        f.write(buffer)
        buffer = next_buffer